apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: example 
spec:
  containers:
    - name: mypod
      image: nginx
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 1Gi
          cpu: 1