#CÓ THẺ HIỂU ENTRYPOINT LÀ LỆNH CHÍNH CỦA CONTAINER, CÒN CMD LÀ THAM SỐ ĐƯỢC TRUYỀN VÀO CHO ENTRYPOINT


#============================CASE 1==============================
# https://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile
# Entrypoint to make container executable, just like ./predict.sh data_path,
# then the predict.sh here is ["echo", "Hello Docker"]
# CÓ thể hiểu đơn giản là ENTRYPOINT là lệnh chính của container, chỉ có thể thêm tham số vào sau chứ không thể thay đổi lệnh linh hoạt như cmd
FROM python:3.9-slim
#biến Dockerfile thành 1 excutable file mà khi chạy container sẽ thực thi lệnh này
ENTRYPOINT ["echo", "Hello Docker"]

# Ví dụ: 
    #docker run myimage # thì câu lệnh full sẽ là echo Hello Docker
    #docker run myimage BYe # thì câu lệnh full sẽ là echo Hello Docker BYe

#============================CASE 2==============================
# CMD to provide default arguments to the entrypoint
# We often use it to pass data to our model as an argument python predict.py --data data_path
FROM python:3.9-slim
ENTRYPOINT ["echo"]
CMD ["Hello Docker"]

# Ví dụ:
    #docker run myimage thì câu lệnh full là echo Hello Docker
    #docker run myimage BYe thì câu lệnh full là echo BYe

# #============================CASE 3==============================
# # Entrypoint can be omited, the default entrypoint will be /bin/sh -c bash
# # We often use this case :)
# Mặc định ENTRYPOINT sẽ là /bin/sh -c
FROM python:3.9-slim

# cho ra câu lệnh /bin/sh -c "echo Hello Docker"
CMD ["echo", "Hello Docker"] 

# Khi chạy docker run myimage date -> /bin/sh -c "date"