# This is to say that build 
# and deploy are not files
.PHONY: build test

test:
	echo "Test something"

build:
	echo "Build something 1"
	
deploy: build #BUILD TRƯỚC
	echo "Deploy something"

ci: test build
